window.GYM_PUBLIC_CONFIG = Object.freeze({
  schemaVersion: 1,
  identity: {
    name: "Demo Gym",
    shortName: "Demo",
    locale: "en-GB",
    timezone: "Etc/UTC",
  },
  branding: {
    logoUrl: "./assets/logo.svg",
    iconUrl: "./assets/icon.svg",
    colors: {
      primary: "#174A5B",
      accent: "#F2B84B",
      background: "#07161C",
      surface: "#FFFFFF",
    },
  },
  scanner: {
    texts: {
      readyTitle: "Scan your member card",
      readyInstruction: "Hold the QR code inside the frame",
      loadingTitle: "Checking you in",
      loadingInstruction: "Please wait",
      successTitle: "Welcome",
      duplicateTitle: "Already checked in",
      notFoundTitle: "Member not found",
      inactiveTitle: "Membership inactive",
      outsideWindowTitle: "Check-in is closed",
      errorTitle: "Unable to check in",
      invalidInstruction: "Please scan a valid member card",
      errorInstruction: "Please try again",
      timeoutTitle: "Connection timed out",
      timeoutInstruction: "Please try again",
      cameraStartingText: "Starting camera",
      cameraActiveText: "Camera active",
      cameraErrorInstruction: "Allow camera access, then retry",
      soundHint: "Tap once to enable sound",
      retryButton: "Retry camera",
    },
    resetMs: {
      success: 15000,
      duplicate: 3500,
      error: 5000,
      outsideWindow: 5000,
    },
    behavior: {
      sound: true,
      vibration: true,
      preferredCamera: "environment",
    },
  },
  integration: {
    checkInEndpoint: "",
    scannerUrl: "",
  },
});
